Hw05 avatars
Oleksii83/nodejs-homework-rest-api pull request #5
Opened 2021-11-28 13:34 UTC by Oleksii83

Необходимо проверить

2021-11-29 12:15 UTC, Danil44 commented
Потрібно почистити закоментований код

2021-11-29 12:15 UTC, Danil44 requested changes

2021-11-29 12:15 UTC, Danil44 commented on controllers/contacts/updateAvatars.js
> +      `${contactId}_${originalname}`
нам потрібно розширення?

2021-12-01 06:23 UTC, Oleksii83 commented on controllers/contacts/updateAvatars.js
> +      `${contactId}_${originalname}`
не понял суть вопроса, ві имеете ввиду расширение файла? так за него отвечает ${originalname}

2021-12-01 12:54 UTC, merged